project_id = "qrzkxhnpxtsicqcpzplc"

[functions.api-auth]
verify_jwt = false

[functions.api-bookings]
verify_jwt = false

[functions.api-matches]
verify_jwt = false

[functions.api-checkins]
verify_jwt = false

[functions.api-customers]
verify_jwt = false

[functions.api-day-passes]
verify_jwt = false

[functions.api-events]
verify_jwt = false

[functions.api-admin]
verify_jwt = false

[functions.api-event-public]
verify_jwt = false
