-- Restore generated event-offer PDFs as a private, server-only capability.
-- No storage.objects policy is created: service-role Edge Functions are the
-- only storage principal, while their venue-admin checks remain the human
-- authorization boundary.

INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'event-offers',
  'event-offers',
  false,
  10485760,
  ARRAY['application/pdf']::text[]
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE OR REPLACE FUNCTION public.is_canonical_event_offer_object_name(p_name text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    p_name ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.pdf$',
    false
  )
$$;

REVOKE ALL ON FUNCTION public.is_canonical_event_offer_object_name(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_canonical_event_offer_object_name(text) TO service_role;

COMMENT ON FUNCTION public.is_canonical_event_offer_object_name(text) IS
  'Validates organization/venue/lead/offer.pdf paths generated by trusted event-offer Edge Functions.';
